### PR TITLE
Added the feature in SheetNameCaptalization to revert back from UpperCase to LowerCase 

### PR DESCRIPTION
**Pull request by ashwanidv100**
Hi, Thanks for sharing this repo as an open-source project, really helps for everyone to learn and grow. Just tested the project and its working perfectly fine.  👍

Added a few lines, If condition to see if sheet Name is already in uppercase then we can revert it to lowercase as well and then click again to make it to uppercase. I will also pull more request. Looking forward to the contribution. 😀

### CODE REVIEW

**Review by TorsionTools — COMMENTED** [review]
Thanks for the feedback! I might be careful with this approach. Its best if a function does exactly what it says and only that. If the Function is "Sheet Name Capitalize" then it should only do that. Also, I would say it would be very rare that you want a sheet name ALL lower, and not at least Title Case.

**Comment by ashwanidv100** [comment]
Then I think it would be good to have rollback on Sheet Name Capitalize to revert back as it was before the Uppercase. 🤔 But yeah it can also simply done via clt+z. Thanks though, will take care of it 🙌

**Comment by TorsionTools** [comment]
Thanks @ashwanidv100, I added and pushed a revision to the Sheet Name Capitalize command to provide a preview very much like the Find Replace. Do you think this helps resolve your concerns? But yes, the "Undo" is still the best way to roll back the Transaction.

**Comment by ashwanidv100** [comment]
Yeah, This looks much better than before.

**Pull request closed without merging**
